import { GoogleGenAI, Modality } from "@google/genai";

// FIX: Per coding guidelines, API key must be obtained exclusively from process.env.API_KEY.
const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  // In a real app, you might want to handle this more gracefully.
  // For this environment, we'll throw an error if the key is missing.
  console.warn("API_KEY environment variable not set. Gemini API calls will fail.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY! });

export const generateBadgeImage = async (streak: number): Promise<string> => {
  if (!API_KEY) {
    // Return a placeholder if API key is not available
    console.log("Using placeholder image due to missing API key.");
    return `https://picsum.photos/seed/${streak}/512`;
  }
  
  try {
    const prompt = `A futuristic, cosmic, glowing badge for a ${streak}-day achievement streak. Electric purple, neon pink and cyan colors on a dark background. Epic trophy design, digital art, cinematic lighting.`;

    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/png',
          aspectRatio: '1:1',
        },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes = response.generatedImages[0].image.imageBytes;
      return `data:image/png;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error("Error generating badge image with Gemini:", error);
    // Fallback to a placeholder image on error
    return `https://picsum.photos/seed/${streak}/512`;
  }
};

export const generateAvatarImage = async (prompt: string): Promise<string> => {
  if (!API_KEY) {
    console.log("Using placeholder image due to missing API key.");
    return `https://picsum.photos/seed/${prompt}/512`;
  }

  try {
    const fullPrompt = `A cool, futuristic profile picture avatar based on this description: "${prompt}". Digital art, cyberpunk style, vibrant neon colors, dark background, cinematic lighting, focused on the face.`;
    
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: fullPrompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/png',
          aspectRatio: '1:1',
        },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes = response.generatedImages[0].image.imageBytes;
      return `data:image/png;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the API for the avatar.");
    }
  } catch (error) {
    console.error("Error generating avatar image with Gemini:", error);
    return `https://picsum.photos/seed/${prompt}/512`;
  }
};

// Helper to convert image URL to a base64 Data URL
const imageUrlToDataUrl = async (url: string): Promise<string> => {
    const response = await fetch(url);
    const blob = await response.blob();
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
};

export const editImage = async (imageUrl: string, prompt: string): Promise<string> => {
  if (!API_KEY) {
    console.warn("API key not set, using placeholder for image edit.");
    // In a real scenario, might return the original image or show an error
    return imageUrl;
  }

  // Ensure image is in base64 format for the API
  let imageDataUrl = imageUrl;
  if (!imageUrl.startsWith('data:')) {
    imageDataUrl = await imageUrlToDataUrl(imageUrl);
  }

  const match = imageDataUrl.match(/^data:(image\/[a-z]+);base64,(.*)$/);
  if (!match) {
    throw new Error('Invalid data URL format for image editing.');
  }
  const [, mimeType, data] = match;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { inlineData: { mimeType, data } },
          { text: prompt },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const base64ImageBytes = part.inlineData.data;
        return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
      }
    }
    throw new Error("No image data in Gemini API response for editing.");
  } catch (error) {
    console.error("Error editing image with Gemini:", error);
    // Fallback to the original image on error
    return imageUrl;
  }
};
